language: python
python:
  - 3.4

services:
  - docker

install:
  - docker build -t hello_ci .
  - docker run -d -p 127.0.0.1:8000:8000 --name hello_ci hello_ci

#before_script:
#  - pip install -r requirements.txt

script:
  - docker ps | grep -q blog
  - python tests.py
