language: python
python:
  - 2.7
  - 3.5
services:
  - docker
  - redis-server
install:
  - docker build -t blog .
  - docker run -d -p 127.0.0.1:80:80 --name blog blog
script:
  - docker ps | grep -q blog

