apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: hello-web
  name: hello-web-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: hello-web
  template:
    metadata:
      labels:
        run: hello-web
    spec:
      containers:
      - image: index.docker.io/swsan/hello:latest
        name: hello-web
        ports:
        - containerPort: 8000   
---
apiVersion: v1
kind: Service
metadata:
  name: hello-web-service 
spec:
  selector:
    run: hello-web 
  type: NodePort
  ports:
  - protocol: TCP
    nodePort: 30080
    targetPort: 8000
    port: 8000
